---
- name: Enable intranet services
  hosts: all
  tasks:
   - name: latest version of httpd installed
     yum:
      name: httpd
      state: latest
     delegate_to: 192.168.0.117
   - name: latest version of firewalld installed
     yum:
      name: firewalld
      state: latest
     delegate_to: 192.168.0.117
   - name: test html page is installed
     become: true
     template:
      src: /root/t.j2
      dest: /var/www/html/index.html
   - name: firewalld enabled and running
     service:
      name: firewalld
      enabled: true
      state: started
     delegate_to: 192.168.0.117
   - name: firewalld permits http service
     firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes
     delegate_to: 192.168.0.117
   - name: httpd enabled and running
     service:
      name: httpd
      enabled: true
      state: started
     delegate_to: 192.168.0.117
