---
- hosts: all
  gather_facts: no
 
  tasks:
    - name: create directory to generate and store reports
      file:
        path: /opt/report
        state: directory
      delegate_to: 192.168.0.117

    - name: create a report data
      setup:
        fact_path: /opt/report
      delegate_to: 192.168.0.117

    - name: generate report
      command: ansible-cmdb /opt/report > /opt/report/system-overview.$(date +%Y%m%d%H%M%S).html
      delegate_to: 192.168.0.117
