---
- hosts: all
  gather_facts: no
 
  tasks:
    - name: create directory to generate and store reports
      file:
        path: /opt/report
        state: directory
      delegate_to: 192.168.0.107

    - name: create a report data
      shell: ansible localhost -m setup  -t /opt/report
      delegate_to: 192.168.0.107

    - name: generate report
      shell: ansible-cmdb /opt/report > /opt/report/system-overview.$(date +%Y%m%d%H%M%S).html
      delegate_to: 192.168.0.107
