---
- hosts: all
  gather_facts: no
 
  tasks:
    - name: create directory to generate and store reports
      file:
        path: /opt/report
        state: directory
      delegate_to: 192.168.0.107

    - name: create a report data
      command: ansible 192.168.0.107 -m setup  -t /opt/report
      delegate_to: localhost
