---
- hosts: all
  gather_facts: no
 
  tasks:
    - name: create directory to generate and store reports
      file:
        path: /opt/report
        state: directory
      delegate_to: 192.168.0.107
      
    - name: create a report data
      setup:
      delegate_to: 192.168.0.117
      register: jstackOut

    - name: write jstack                                                                                
     copy:                                                                                              
       content: "{{jstackOut.stdout}}" 
       dest: /opt/f.txt
